
DROP TABLE IMS_PO_LINE;
DROP TABLE IMS_PURCHASE_ORDER;
DROP TABLE PRODUCT_CATEGORIES;
DROP TABLE IMS_PRODUCT;
DROP TABLE IMS_PRODUCT_CATEGORY;
DROP TABLE IMS_PRODUCT_IMAGE;
DROP TABLE IMS_CLIENT;
DROP TABLE IMS_CLIENT_TYPE;
DROP TABLE IMS_ADDRESS;


CREATE TABLE IMS_ADDRESS (
  IMS_ADDRESS_ID NUMBER PRIMARY KEY,
  STREET_ADDRESS_1 VARCHAR2(250) NOT NULL,
  STREET_ADDRESS_2 VARCHAR2(50),
  ADDRESS_CITY VARCHAR2(35) NOT NULL,
  STATE_ID NUMBER NOT NULL,
  ADDRESS_ZIP VARCHAR2(10) NOT NULL,
  
  CONSTRAINT STATE_ABBRV_FK
    FOREIGN KEY (STATE_ID)
    REFERENCES IMS_STATE_ABBRV(ABBRV_ID)
);

CREATE TABLE IMS_CLIENT_TYPE (
  CLIENT_TYPE_ID NUMBER PRIMARY KEY,
  CLIENT_TYPE VARCHAR2(25) NOT NULL
);

CREATE TABLE IMS_CLIENT (
  IMS_CLIENT_ID NUMBER PRIMARY KEY,
  CLIENT_NAME VARCHAR2(100) NOT NULL,
  CLIENT_EMAIL VARCHAR2(250) NOT NULL,
  POINT_OF_CONTACT_NAME VARCHAR2(250) NOT NULL,
  CLIENT_PHONE VARCHAR2(15) NOT NULL,
  CLIENT_FAX VARCHAR2(15) NOT NULL,
  ADDRESS_ID NUMBER UNIQUE NOT NULL,
  CLIENT_TYPE_ID NUMBER NOT NULL,
  
  CONSTRAINT ADDRESS_FK
    FOREIGN KEY (ADDRESS_ID)
    REFERENCES IMS_ADDRESS(IMS_ADDRESS_ID),
    
  CONSTRAINT CLIENT_TYPE_FK
    FOREIGN KEY (CLIENT_TYPE_ID)
    REFERENCES IMS_CLIENT_TYPE(CLIENT_TYPE_ID)
);

CREATE TABLE IMS_PRODUCT_IMAGE (
  IMAGE_ID NUMBER PRIMARY KEY,
  IMAGE_ADDRESS VARCHAR2(2000) NOT NULL
);

CREATE TABLE IMS_PRODUCT_CATEGORY (
  CATEGORY_ID NUMBER PRIMARY KEY,
  CATEGORY_DESCRIPTION VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE IMS_PRODUCT (
  PRODUCT_UPC NUMBER PRIMARY KEY,
  PRODUCT_NAME VARCHAR2(150) NOT NULL,
  PRODUCT_DESCRIPTION VARCHAR2(250) NOT NULL,
  SHORT_NAME VARCHAR2(5) NOT NULL,
  UNIT_COST NUMBER NOT NULL,
  PACK_SIZE VARCHAR2(10) NOT NULL,
  REORDER_QUANTITY NUMBER NOT NULL,
  RETAIL_PRICE NUMBER NOT NULL,
  PRODUCT_WEIGHT NUMBER,
  PRODUCT_IMAGE_ID NUMBER,
  
  CONSTRAINT IMAGE_FK
    FOREIGN KEY (PRODUCT_IMAGE_ID)
    REFERENCES IMS_PRODUCT_IMAGE(IMAGE_ID)
);

CREATE TABLE PRODUCT_CATEGORIES (
  PRODUCT_UPC NUMBER,
  CATEGORY_ID NUMBER,
  
  CONSTRAINT PRODUCT_CATEGORIES_PK
    PRIMARY KEY (PRODUCT_UPC, CATEGORY_ID),
    
  CONSTRAINT PRODUCT_FK
    FOREIGN KEY (PRODUCT_UPC)
    REFERENCES IMS_PRODUCT(PRODUCT_UPC),
    
  CONSTRAINT CATEGORY_FK
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES IMS_PRODUCT_CATEGORY(CATEGORY_ID)
);

CREATE TABLE IMS_PURCHASE_ORDER (
  ORDER_NUMBER NUMBER PRIMARY KEY,
  SUBTOTAL NUMBER NOT NULL,
  PURCHASE_DATE DATE NOT NULL,
  TAX_AMOUNT NUMBER NOT NULL,
  PO_TOTAL NUMBER NOT NULL,
  CLIENT_ID NUMBER NOT NULL,
  
  CONSTRAINT CLIENT_FK
    FOREIGN KEY (CLIENT_ID)
    REFERENCES IMS_CLIENT(IMS_CLIENT_ID)
);

CREATE TABLE IMS_PO_LINE (
  ORDER_NUMBER NUMBER,
  LINE_NUMBER NUMBER,
  UNIT_PRICE NUMBER NOT NULL,
  QUANTITY_ORDERED NUMBER NOT NULL,
  PRODUCT_UPC NUMBER NOT NULL,
  
  CONSTRAINT IMS_PO_LINE_PK
    PRIMARY KEY (ORDER_NUMBER, LINE_NUMBER),
  
  CONSTRAINT PO_FK
    FOREIGN KEY (ORDER_NUMBER)
    REFERENCES IMS_PURCHASE_ORDER(ORDER_NUMBER),
    
  CONSTRAINT PRODUCT_FKv2
    FOREIGN KEY (PRODUCT_UPC)
    REFERENCES IMS_PRODUCT(PRODUCT_UPC)
);
